### ISSUE TITLE
Rebrand

### ISSUE THREAD

**Issue by jariz** [jariz/Dumpert#11]
Op last van GeenStijl is de app nu offline gehaald uit de play store (door mijzelf).
We kunnen hem pas weer launchen als de app een nieuwe naam heeft en het logo van dumpert niet meer gebruikt (of tenminste in een iets meer subtiele manier).
Eventuele ideen voor een nieuwe naam / nieuw icoon zijn welkom.

**Comment by KeizerDev** [comment]
`Dumbpret`

**Comment by GijsTimmers** [comment]
Het icoon is nu min of meer een kroon. Vervangen door een ander hoofddeksel? Pet, carnavalssteek, ...

**Comment by CytoDev** [comment]
Je zou het icoontje [hier](http://gscdn.nl/dump/images/desktop_header.jpg) van kunnen afleiden. Mensen weten gelijk wat er bedoelt wordt, en je schendt niemands auteursrecht.

**Comment by KeizerDev** [comment]
Laten we dat als profiel/account achtergrond gebruiken (https://raw.githubusercontent.com/mikepenz/MaterialDrawer/develop/DEV/github/screenshots1.jpg) en dus ook dat te implementeren.

**Comment by jariz** [comment]
@KeizerDev first things first :stuck_out_tongue: 
We hebben nu nog niet eens account management erin zitten en ik zie een rebrand liever zien gebeuren voordat we dat hebben.

**Comment by CytoDev** [comment]
Inloggen en commentaar plaatsen is ook een verhaal appart. Registratie loopt via geenstijl, en je hebt koekjes gebakken en wel nodig om commentaar te leveren op dumpert.  
  
Een hele library heb je tevens niet langer nodig. Als je in Android Studio een nieuwe activiteit aan maakt kan je een navdrawer laten maken conform de regeltjes van google.  
  
Ik heb er eventueel nog wel eentje rond slingeren.

**Comment by GijsTimmers** [comment]
Eventueel als logo: een afvoerputje. Past bij de naam, en ook bij de inhoud :laughing:

**Comment by jariz** [comment]
@CytoDev ik heb lang, lang geleden een shitty implementatie geschreven voor inloggen op een GS-website.
Interessant maybe?
https://github.com/jariz/GeenStijl/blob/master/src/io/jari/geenstijl/API/API.java#L276

Anyway, we raken een beetje offtopic. :stuck_out_tongue:

**Comment by CytoDev** [comment]
@jariz, je kan een feature request maken van issue #14. Ik zal er dan gelijk even op duiken. Kan dit draadje weer verder met de rebrand.

**Comment by CytoDev** [comment]
@jariz why not use a new label [General Discussion]? You're just doubling the tags now :laughing:

**Comment by jariz** [comment]
Fair enough.

**Comment by jariz** [comment]
Settled on 'Dump for Dumpert.nl' (playstore title) and 'Dump' (app title) for now. Unless someone has a better idea, I'll stick with this for now.

**Comment by CytoDev** [comment]
Aangezien ik nog geen suggestie had geplaatst over de naam. Bij deze: "De reaguur-app". Vreeslijke naam, maar het klopt op zich wel nu er ook mee gereaguurd(?) kan worden. Vraag me echter wel af of het "werkwoord" reaguren gecopytrademarked is door Dumpert/Geenstijl...

**Comment by KeizerDev** [comment]
@CytoDev `Reaguurders-app` zie ik dan meer zitten.

**Comment by jariz** [comment]
Ik vindt reaguurders-app vreselijk 😶

**Comment by CytoDev** [comment]
En daarom dat dit dus ook het label "discussion" heeft. :laughing:

**Comment by KeizerDev** [comment]
@jariz door het sluiten van dit issue neem ik aan dat er is gekozen voor "De reaguur-app"?

**Comment by jariz** [comment]
Ik wou niet de project owner card pullen maar umm yea, `Dump` vind ik toch het minst ergst vrees ik.
