### ISSUE TITLE
White text on settings activity

### ISSUE THREAD

**Issue by jariz** [jariz/Dumpert#16]
Only showing on the settings activity, but still pretty unreadable.
Happens on all themes.

**Comment by CytoDev** [comment]
already fixed.

**Comment by CytoDev** [comment]
Error info alertdialogs also feature white on white text. I believe it has something to do with the navigation library. Since the last update on their side text started acting weird, and this app does extend it's theme.

**Comment by jariz** [comment]
This is indeed fixed now (merged your dev branch into master just now)
