### ISSUE TITLE
Rename video quality options

### ISSUE THREAD

**Issue by GijsTimmers** [jariz/Dumpert#18]
Running Dumpert Reader f7c28ea5b19adbaa43c7bf3b85d18fa485c44d74.

Menu > Settings > Video quality

Currently, there are two options:

- HQ
- HD

I take it that _HQ_ stands for _High Quality_ and _HD_ stands for _High Defintition_. That said, I have no idea which one I have to choose to get the best video quality

Proposal: rename _HQ_ / _HD_ to _High_ / _Medium_ (or something like that)

**Comment by jariz** [comment]
Great idea, I can totally see why that would be confusing, just added it.

**Comment by KeizerDev** [comment]
Thereby we have a lot more qualities to choose from: 
```
{
"flv":"http:\/\/media.dumpert.nl\/flv\/6066c68f_160106_DUMPERTREETEN36.mp4.mp4.flv",
"tablet":"http:\/\/media.dumpert.nl\/tablet\/6066c68f_160106_DUMPERTREETEN36.mp4.mp4.mp4",
"mobile":"http:\/\/media.dumpert.nl\/mobile\/6066c68f_160106_DUMPERTREETEN36.mp4.mp4.mp4",
"720p":"http:\/\/media.dumpert.nl\/720p\/6066c68f_160106_DUMPERTREETEN36.mp4.mp4.mp4",
"still":"http:\/\/media.dumpert.nl\/stills\/6709042_6066c68f.jpg"
}
```

So I suggest to choose a default quality in the settings and an extra option in the player itself to change the quality on the fly.

**Comment by KeizerDev** [comment]
So lets pretend that 
```
mobile: 360p
tablet: 480p
720p: 720p
```

**Comment by CytoDev** [comment]
@KeizerDev I wouldn't suggest 360p for mobile. Most modern phones have at least a 480p compatible screen. I would say low quality could be 360, but then again, who wants to watch low quality videos?

**Comment by KeizerDev** [comment]
@CytoDev I mean, `mobile` is equals to 360p and `tablet` to 480p, look at the player quality options (http://www.dumpert.nl/mediabase/6709042/6066c68f/dumpertreeten_%2836%29.html). Imho I do like to see *360p* instead of *low quality*.

**Comment by KeizerDev** [comment]
And when on mobile network it would be cool to set your preferred quality and change it on the fly.
