### ISSUE TITLE
DR starts playing video after locking the screen

### ISSUE THREAD

**Issue by GijsTimmers** [jariz/Dumpert#19]
Running Dumpert Reader f7c28ea5b19adbaa43c7bf3b85d18fa485c44d74 on Kitkat.

How to reproduce:

1. Open a video
2. (Video starts playing automatically)
3. Press the full screen button in the bottom right of the screen
4. Pause the video
5. Press the lock screen button

Now, Dumpert Reader will continue playing the video while the screen is off.

**Comment by CytoDev** [comment]
I am aware of this bug. This seems to happen when the system decides to recycle the activity or free up resources.

**Comment by CytoDev** [comment]
@GijsTimmers can you test with my fix please?

**Comment by GijsTimmers** [comment]
Sure. I'll report back asap.

**Comment by GijsTimmers** [comment]
Works!

**Comment by CytoDev** [comment]
Nice!
