### ISSUE TITLE
Finish reload button on video error snackbar

### ISSUE THREAD

**Issue by jariz** [jariz/Dumpert#20]
The button's there but doesn't do anything yet. (VideoActivity.java:135)

**Comment by CytoDev** [comment]
Just put that there to have at least a way to reload the video (and if it works other elements). It doesn't work yet because I don't know how to reload the fragment and keep the data it's supposed to have.

**Comment by jariz** [comment]
Yea, I figured, just wanted to make sure we don't forget about it.

**Comment by CytoDev** [comment]
Is there any reason why we currently use a third party snackbar? Can't seem to find backwards-compatibility issues with the one in the Google design libs...

**Comment by jariz** [comment]
Google didn't have a design library yet when I started working on this, same reason I used a 3rd party navdrawer.

**Comment by CytoDev** [comment]
Check the latest commit in snackBar and see if you like it. You can test it by searching for "fapvoer" and clicking any video (I disabled NSFW video loading to test this).

**Comment by CytoDev** [comment]
Should all be finished in [#6b3b4d2](https://github.com/jariz/Dumpert/commit/6b3b4d2262ccc9d836844856ae00c6e34c1ca4ca). Please double check it @jariz

**Comment by CytoDev** [comment]
Can't get the error alertdialog to grab the right colours though...

**Comment by jariz** [comment]
Maybe create a separate issue for that? Reload button works fine for me (which is the scope of this ticket), so I merged it.

**Comment by CytoDev** [comment]
I don't see the merge though...

**Comment by jariz** [comment]
@CytoDev look again! 🙈

**Comment by CytoDev** [comment]
Everything's up to date now yeh? I always seem to stop doing the thinky thing when multiple branches get merged...

**Comment by jariz** [comment]
Yes. I should file a PR in the future like you did with themeCrash, makes it more clear, but yes it is.

**Comment by CytoDev** [comment]
Cool. I'll take a look at the video reloading now then.
