### ISSUE TITLE
AlertDialog displays with white colors dispite being told to use a custom theme

### ISSUE THREAD

**Issue by CytoDev** [jariz/Dumpert#22]
Pretty much sums it up.

**Comment by CytoDev** [comment]
This bug can be tracked down to the MaterialNavigationDrawer used in the app. I suggest moving away from it, or using a dark theme for the AlertDialog.

@jariz, thoughts?

**Comment by CytoDev** [comment]
I got it working by changing the theme of the application to `Theme.Dumpert` instead of `Theme.Dumpert.Drawer`. The only downside is... Well, see for yourself:
![device-2016-01-07-170435__alert_working](https://cloud.githubusercontent.com/assets/5646869/12175141/f7a27d7c-b560-11e5-9762-98f6f1fae4dc.png)
![device-2016-01-07-170435__alert_downside](https://cloud.githubusercontent.com/assets/5646869/12175147/fbe673de-b560-11e5-8154-75e64ffe5103.png)

**Comment by CytoDev** [comment]
I think the only feasible way of fixing this issue is to implement the navigation drawer from the AppCompat library... Or removing the error message, but I don't think that's such a good idea.

**Comment by jariz** [comment]
Yea, we need to get rid of that annoying deprecated library eitherway, so +1 to getting rid of it and replacing it with design library.
I suggest doing this after the re-release though, and showing a dark dialog as a 'fix' until we fix it properly.

**Comment by CytoDev** [comment]
@jariz Are you in a rush to the milestone? I can implement the drawer by the end of this weekend. Give or take a few minor bugs that are part of the migration and can be easily fixed.

**Comment by jariz** [comment]
@CytoDev Not in a rush, just wanna launch it soon.
If you think by the end of this weekend it can be done, then it's fine by me.

**Comment by CytoDev** [comment]
Closed by [#f0b2845](https://github.com/jariz/Dumpert/commit/f0b2845cd104ce4c4d3afd568e98108729cca096).
