### ISSUE TITLE
On the usefulness of landscape mode for videos

### ISSUE THREAD

**Issue by GijsTimmers** [jariz/Dumpert#29]
Disclaimer: I'm using a 720x1280 px screen, so your mileage may vary.

At the moment, there are four modes of playing videos

- Portrait mode
- Portrait mode, fullscreen (the new feature)
- Landscape mode
- Landscape mode, fullscreen

I don't know about you, but I don't consider the third mode to be very useful. The amount of screen real estate is very much reduced. From top to bottom:

![screenshot_2016-01-08-10-32-40](https://cloud.githubusercontent.com/assets/972314/12194984/7169efbc-b5f4-11e5-88e2-de49007782b0.png)

- We have the Android statusbar
- Then, there is the DR titlebar
- Video part
- Comments part

These parts severely reduce the allowed height of the video. Because the media player likes to respect the width/height ratio, it reduces the width of the video, too. So we end up with a very small video size.

Moreover, the comments part is quite small. It may be my fat fingers but the amount of space allows _just_ my thumb to be put there to scroll. That makes it very hard to scroll fast, as you have to put your finger on the same spot over and over again. Currently, there's room for about 1 comment.

Proposal: ditch the current landscape mode. Activate the fullscreen landscape mode whenever a rotation to landscape mode is detected.

**Comment by CytoDev** [comment]
I for one, __hate__ landscape mode. Seriously, F auto-rotation and everyone who uses it.

**Comment by jariz** [comment]
I say we force portrait on that activity. Not worth the effort optimizing it for landscape for those few that use portrait.

**Comment by CytoDev** [comment]
@jariz on the video activity, or just the general itemView layout? Images will have the same issue as described above, while audio might be small enough to not bother anyone to tears.
