### ISSUE TITLE
Topexception handler.

### ISSUE THREAD

**Issue by CytoDev** [jariz/Dumpert#34]
Perhaps it would also be a good idea to implement a top exception handler and prevent all future crashes? I did it before, so it shouldn't be that hard to do it again. It would require an intent to send the collected data to "The developers" though...

**Comment by jariz** [comment]
1. Crashes happen for a reason, it's because the exception is unhandled, which is something that generally only happens when things went really far south.
2. This would prevent people from reporting errors to the play store.

Generally, I don't like this idea.

**Comment by CytoDev** [comment]
Most crashes are unnecessary though. Some activities crash when the server does not respond with the answer that is built in to be parsed.  
  
Agreed that exceptions should be caught over there though.

**Comment by CytoDev** [comment]
I hate the mobile github layout...

**Comment by KeizerDev** [comment]
@CytoDev lol +1

**Comment by jariz** [comment]
Then like you said yourself, maybe exception handling should be improved overall.

**Comment by GijsTimmers** [comment]
I'd be against it, for the same reasons @jariz is. Also, the 'testing team' on Github consists of four (five?) people. There may very well be bugs in the code that just don't show up on our devices. In other words, _n_ is too small.

**Comment by CytoDev** [comment]
Closing issue and opting to have better error catching.
