### ISSUE TITLE
Can't scroll past 15th item in Toppers

### ISSUE THREAD

**Issue by GijsTimmers** [jariz/Dumpert#36]
When I scroll to item 15 in _Nieuw_, DR automatically loads item 16-30. This does not happen in _Toppers_. Instead, an error message appears:

    Items ophalen mislukt.

**Comment by CytoDev** [comment]
I get the error that the URL could not be parsed.

**Comment by GijsTimmers** [comment]
That's possible. I'm still using the white-text-on-white-background version.

**Comment by CytoDev** [comment]
Fixed in newNavDrawer branch. Needed an extra slash after the fetching url.
