### ISSUE TITLE
Crash on pressing the back button in settings

### ISSUE THREAD

**Issue by GijsTimmers** [jariz/Dumpert#48]
[Log](http://paste.ubuntu.com/14488419/)

**Comment by CytoDev** [comment]
Crash at line 4524. Could you pipe it to grep "Exception" next time, please?

**Comment by CytoDev** [comment]
onCreate() line 63 has a nullpointer on returning from the settings. Will look into it when I'm home.

**Comment by CytoDev** [comment]
Try it with [this branch](https://github.com/jariz/Dumpert/tree/patch-48).

**Comment by GijsTimmers** [comment]
Thank you, that seems to fix it. Minor issue left: when pressing the back button, I get back to _New_. It would be nice if DR would remember on which page I was and return accordingly.

**Comment by jariz** [comment]
It would be even nicer even settings were opened in a fragment rather than a activity imo.

**Comment by CytoDev** [comment]
@jariz read the code. It is a fragment. It needs an activity to apply the toolbar.  
@GijsTimmers You cannot be returned to the page you where on since the activity needs to be restarted in case the theme changed.
