### ISSUE TITLE
Rename repo to Dump

### ISSUE THREAD

**Issue by jariz** [jariz/Dumpert#61]

**Comment by KeizerDev** [comment]
No, don't do that, just put it in the description.

**Comment by GijsTimmers** [comment]
I do like it.

**Comment by KeizerDev** [comment]
@GijsTimmers Why? If someone search for it on gh it is harder to find the repo?

**Comment by GijsTimmers** [comment]
Right now, the repo name is different from the app name. I may be the only one but that inconsistency bothers me a little bit.

**Comment by KeizerDev** [comment]
Than call it "Dump for Dumpert"

**Comment by GijsTimmers** [comment]
Yes, I'm fine with that

**Comment by jariz** [comment]
I think DumpForDumpert is too long and sounds stupid. Think I'll just keep the current name for now because of above mentioned reasons.

**Comment by KeizerDev** [comment]
Can be closed.
